kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:openshift:operator:etcd-backup-role
rules:
  - apiGroups:
      - "operator.openshift.io"
    resources:
      - "etcdbackups"
    verbs:
      - "create"
