apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:etcd-backup-crb
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
roleRef:
  kind: ClusterRole
  name: system:openshift:operator:etcd-backup-role
subjects:
  - kind: ServiceAccount
    namespace: openshift-etcd
    name: etcd-backup-sa
