apiVersion: v1
kind: Secret
metadata:
  name: etcd-metric-signer
  namespace: openshift-config
  annotations:
    openshift.io/owning-component: Etcd
type: kubernetes.io/tls
data:
  tls.crt: {{ .EtcdMetricSignerCert | base64 }}
  tls.key: {{ .EtcdMetricSignerKey | base64 }}
