apiVersion: v1
kind: Secret
metadata:
  name: etcd-client
  namespace: openshift-config
  annotations:
    openshift.io/owning-component: Etcd
type: kubernetes.io/tls
data:
  tls.crt: {{ .EtcdSignerClientCert | base64 }}
  tls.key: {{ .EtcdSignerClientKey | base64 }}
