apiVersion: v1
kind: Secret
metadata:
  name: etcd-metric-client
  namespace: openshift-config
  annotations:
    openshift.io/owning-component: Etcd
type: kubernetes.io/tls
data:
  tls.crt: {{ .EtcdMetricSignerClientCert | base64 }}
  tls.key: {{ .EtcdMetricSignerClientKey | base64 }}
